#!/usr/bin/env python3
"""
Enrich the math Q&A pool with long, detailed answers generated by MiniMax.

Selects hard math problems from the pool, sends each to MiniMax with a prompt
that requests extremely detailed step-by-step solutions, and saves the
resulting long-answer records (same format as math_pool.jsonl).

Usage:
  python enrich_pool.py \\
      --pool math_pool.jsonl \\
      --output math_pool_enriched.jsonl \\
      --api_key_file ~/llm_keys/minimax \\
      --num_samples 200

Resume from checkpoint:
  python enrich_pool.py \\
      --pool math_pool.jsonl \\
      --output math_pool_enriched.jsonl \\
      --api_key_file ~/llm_keys/minimax \\
      --resume checkpoint.json
"""
import os
import json
import time
import random
import argparse
import hashlib
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Dict, Set, Optional, Tuple, Any

try:
    from urllib.request import Request, urlopen
    from urllib.error import HTTPError, URLError
except ImportError:
    from urllib2 import Request, urlopen, HTTPError, URLError

from transformers import AutoTokenizer

# ---------------------------------------------------------------------------
# Prompt that asks MiniMax for extremely detailed solutions
# ---------------------------------------------------------------------------
DETAILED_SYSTEM = (
    "You are a mathematics professor. Provide solutions that are extremely "
    "detailed, thorough, and comprehensive — as if writing a textbook chapter. "
    "Every step must be fully explained. Leave no detail unexplained."
)

DETAILED_USER = """Please solve the following math problem with EXTREMELY detailed, step-by-step reasoning. Your solution should be as comprehensive as possible.

For each step you MUST:
- State the theorem, formula, or concept being applied
- Explain WHY this specific approach is correct
- Show ALL calculations and algebraic manipulations in full detail (do not skip any)
- Verify intermediate results
- If multiple approaches exist, briefly mention and compare them

Make your answer as long and detailed as possible while remaining mathematically rigorous.

Problem: {question}

Provide your complete, detailed solution:"""

# OpenAI-compatible chat completions body template
# temperature is dynamically varied per request for diversity
API_MAX_TOKENS = 8192
API_TIMEOUT = 180  # seconds
MAX_RETRIES = 3
RETRY_DELAY = 5  # seconds (exponential backoff: delay * (2 ** attempt))


# ---------------------------------------------------------------------------
# Problem selection
# ---------------------------------------------------------------------------

def add_short_records(
    pool: List[Dict],
    max_answer_tokens: int = 200,
    max_total_tokens: int = 500,
    max_per_source: int = 100,
    seed: int = 42,
) -> List[Dict]:
    """Select short-answer records for fine-grained prompt packing.

    Returns records with modified source labels (enriched_short_{src})
    and new IDs (enriched_short_{original_id}).
    """
    rng = random.Random(seed)

    by_source: Dict[str, List[Dict]] = {}
    for r in pool:
        if (r.get("answer_tokens", 0) <= max_answer_tokens
                and r.get("total_tokens", 0) <= max_total_tokens):
            src = r.get("source", "unknown")
            by_source.setdefault(src, []).append(r)

    selected: List[Dict] = []
    for src, candidates in sorted(by_source.items()):
        rng.shuffle(candidates)
        take = min(max_per_source, len(candidates))
        chosen = candidates[:take]
        for r in chosen:
            rec = dict(r)
            rec["id"] = f"enriched_short_{r['id']}"
            rec["source"] = f"enriched_short_{src}"
            rec["original_id"] = r["id"]
            selected.append(rec)

    print(f"  Short records selected: {len(selected)} "
          f"(max_answer_tokens<={max_answer_tokens}, "
          f"max_total_tokens<={max_total_tokens})")
    for src in sorted(by_source.keys()):
        cnt = sum(1 for r in selected if r["source"] == f"enriched_short_{src}")
        if cnt:
            print(f"    enriched_short_{src}: {cnt}")
    return selected


def select_hard_problems(
    pool: List[Dict],
    num_samples: int = 200,
    seed: int = 42,
) -> List[Dict]:
    """Select diverse hard problems via stratified sampling across sources.

    Priority order:
    1. AIME 2024 + 2025 — hardest, take all (usually ~60 total)
    2. MATH-500 — competition math, top-100 by existing answer_tokens
    3. DAPO-Math-17k — diverse topics, random 40
    """
    rng = random.Random(seed)

    by_source: Dict[str, List[Dict]] = {}
    for r in pool:
        src = r.get("source", "unknown")
        by_source.setdefault(src, []).append(r)

    selected: List[Dict] = []

    # AIME — take all (rarest and hardest)
    for aime_src in ["aime2024", "aime2025"]:
        if aime_src in by_source:
            candidates = list(by_source[aime_src])
            rng.shuffle(candidates)
            selected.extend(candidates)
            print(f"  AIME ({aime_src}): {len(candidates)} problems")

    # MATH-500 — top by answer token length (indicates complex problems)
    if "math_500" in by_source:
        candidates = sorted(
            by_source["math_500"],
            key=lambda r: r.get("answer_tokens", 0),
            reverse=True,
        )
        take = min(100, len(candidates))
        selected.extend(candidates[:take])
        print(f"  MATH-500: {take} problems (by answer_tokens desc)")

    # DAPO-Math-17k — random sample for topic diversity
    if "dapo_math_17k" in by_source:
        candidates = list(by_source["dapo_math_17k"])
        rng.shuffle(candidates)
        take = min(40, len(candidates))
        selected.extend(candidates[:take])
        print(f"  DAPO-Math-17k: {take} problems (random)")

    # GSM8K (train) — top by answer_tokens as fallback to fill quota
    if "gsm8k" in by_source:
        candidates = sorted(
            by_source["gsm8k"],
            key=lambda r: r.get("answer_tokens", 0),
            reverse=True,
        )
        take = min(50, len(candidates))
        selected.extend(candidates[:take])
        print(f"  GSM8K: {take} problems (by answer_tokens desc)")

    # Deduplicate by id (in case of cross-source overlap)
    seen: Set[str] = set()
    unique: List[Dict] = []
    for r in selected:
        if r["id"] not in seen:
            unique.append(r)
            seen.add(r["id"])

    rng.shuffle(unique)
    if len(unique) > num_samples:
        unique = unique[:num_samples]

    print(f"  Total selected: {len(unique)} problems (after dedup, target={num_samples})")
    return unique


# ---------------------------------------------------------------------------
# MiniMax API call (OpenAI-compatible)
# ---------------------------------------------------------------------------

def call_minimax(
    question: str,
    api_key: str,
    api_base: str,
    model: str,
    temperature: float,
    max_tokens: int = API_MAX_TOKENS,
    timeout: int = API_TIMEOUT,
) -> str:
    """Call MiniMax chat completions API (OpenAI-compatible). Returns answer text."""
    url = f"{api_base}/chat/completions"

    messages = [
        {"role": "system", "content": DETAILED_SYSTEM},
        {"role": "user", "content": DETAILED_USER.format(question=question)},
    ]

    body = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "stream": False,
    }

    data = json.dumps(body).encode("utf-8")
    req = Request(url, data=data)
    req.add_header("Content-Type", "application/json")
    req.add_header("Authorization", f"Bearer {api_key}")

    last_error = None
    for attempt in range(MAX_RETRIES):
        try:
            resp = urlopen(req, timeout=timeout)
            result = json.loads(resp.read().decode("utf-8"))
            return result["choices"][0]["message"]["content"]
        except HTTPError as e:
            err_body = ""
            try:
                err_body = e.read().decode("utf-8")[:500]
            except Exception:
                pass
            last_error = RuntimeError(f"HTTP {e.code}: {err_body}")
            if e.code == 429 or e.code >= 500:
                delay = RETRY_DELAY * (2 ** attempt)
                print(f"    Retry {attempt + 1}/{MAX_RETRIES} after {delay}s "
                      f"(HTTP {e.code})")
                time.sleep(delay)
            else:
                raise last_error
        except (URLError, OSError) as e:
            last_error = RuntimeError(f"Connection error: {e}")
            if attempt < MAX_RETRIES - 1:
                delay = RETRY_DELAY * (2 ** attempt)
                print(f"    Retry {attempt + 1}/{MAX_RETRIES} after {delay}s")
                time.sleep(delay)

    raise last_error  # type: ignore[misc]


# ---------------------------------------------------------------------------
# Main enrichment loop
# ---------------------------------------------------------------------------

def load_pool(pool_path: str) -> List[Dict]:
    """Load math Q&A pool from JSONL file."""
    records = []
    with open(pool_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def make_record_id(original_id: str, model: str) -> str:
    """Create a deterministic enriched record id."""
    raw = f"enriched_{model}_{original_id}"
    return hashlib.md5(raw.encode()).hexdigest()[:16]


def load_checkpoint(checkpoint_path: str) -> Dict:
    """Load checkpoint for resume."""
    with open(checkpoint_path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_checkpoint(
    checkpoint_path: str,
    completed: List[Dict],
    remaining: List[Dict],
    args: Dict,
):
    """Save progress checkpoint (overwrites)."""
    state = {
        "completed": completed,
        "completed_ids": [r["id"] for r in completed],
        "remaining_ids": [r["id"] for r in remaining],
        "args": args,
    }
    with open(checkpoint_path, "w", encoding="utf-8") as f:
        json.dump(state, f, ensure_ascii=False, indent=2)


def save_records(records: List[Dict], output_path: str):
    """Save enriched records as JSONL."""
    with open(output_path, "w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")


def main():
    parser = argparse.ArgumentParser(
        description="Enrich math pool with long MiniMax-generated answers"
    )
    parser.add_argument("--pool", type=str, default="math_pool.jsonl",
                        help="Path to math Q&A pool JSONL")
    parser.add_argument("--output", type=str, default="math_pool_enriched.jsonl",
                        help="Output path for enriched records (JSONL)")
    parser.add_argument("--num_samples", type=int, default=200,
                        help="Number of problems to enrich")
    parser.add_argument("--api_key_file", type=str, default=None,
                        help="Path to file containing MiniMax API key "
                             "(required for API enrichment, optional with --add_short_from)")
    parser.add_argument("--add_short_from", type=str, default=None,
                        help="Path to pool JSONL to draw short-answer records from. "
                             "Appends records with enriched_short_* source labels "
                             "for fine-grained prompt packing.")
    parser.add_argument("--short_max_answer_tokens", type=int, default=200,
                        help="Max answer tokens for short records (default 200)")
    parser.add_argument("--short_max_total_tokens", type=int, default=500,
                        help="Max total tokens (Q+A) for short records (default 500)")
    parser.add_argument("--short_max_per_source", type=int, default=100,
                        help="Max short records per source dataset (default 100)")
    parser.add_argument("--api_base", type=str,
                        default="https://api.minimaxi.com/v1",
                        help="MiniMax API base URL (OpenAI-compatible)")
    parser.add_argument("--model", type=str, default="MiniMax-M2.5",
                        help="MiniMax model name")
    parser.add_argument("--temperature_low", type=float, default=0.7,
                        help="Min temperature for diversity (random per request)")
    parser.add_argument("--temperature_high", type=float, default=0.9,
                        help="Max temperature for diversity (random per request)")
    parser.add_argument("--max_output_tokens", type=int, default=API_MAX_TOKENS,
                        help="Max output tokens per request")
    parser.add_argument("--tokenizer_path", type=str, default="./DeepSeekR1",
                        help="Path to tokenizer for counting tokens in outputs")
    parser.add_argument("--seed", type=int, default=42,
                        help="Random seed for problem selection")
    parser.add_argument("--resume", type=str, default=None,
                        help="Resume from checkpoint JSON file")
    parser.add_argument("--checkpoint_interval", type=int, default=3,
                        help="Save checkpoint every N completed requests")
    parser.add_argument("--workers", type=int, default=5,
                        help="Number of concurrent API workers (default 5)")
    parser.add_argument("--delay", type=float, default=2.0,
                        help="Delay in seconds between API call submissions "
                             "(to avoid rate limits)")
    args = parser.parse_args()

    # Read API key (required for enrichment, optional for --add_short_from only)
    api_key = None
    if args.api_key_file:
        with open(os.path.expanduser(args.api_key_file), "r", encoding="utf-8") as f:
            api_key = f.read().strip()
        if not api_key:
            parser.error(f"API key file is empty: {args.api_key_file}")

    do_enrich = api_key is not None
    do_add_short = args.add_short_from is not None

    if not do_enrich and not do_add_short:
        parser.error("Either --api_key_file (for API enrichment) or "
                     "--add_short_from (to add short records) is required")

    # Ensure offline tokenizer loading (no HF hub calls)
    os.environ.setdefault("HF_HUB_OFFLINE", "1")
    os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")

    rng = random.Random(args.seed)
    completed_order: List[Dict] = []
    checkpoint_path = args.resume or (args.output + ".checkpoint.json")

    # ------------------------------------------------------------------
    # API enrichment (optional)
    # ------------------------------------------------------------------
    if do_enrich:
        print(f"Loading tokenizer from {args.tokenizer_path}...", flush=True)
        tokenizer = AutoTokenizer.from_pretrained(
            args.tokenizer_path, trust_remote_code=True, local_files_only=True)
        print(f"  Tokenizer loaded.", flush=True)

        # Load pool
        print(f"Loading pool from {args.pool}...", flush=True)
        pool = load_pool(args.pool)
        print(f"  Loaded {len(pool)} records", flush=True)

        # Handle resume
        completed: List[Dict] = []
        if args.resume and os.path.exists(args.resume):
            print(f"Resuming from checkpoint: {args.resume}")
            ckpt = load_checkpoint(args.resume)
            completed = ckpt["completed"]
            remaining_ids: Set[str] = set(ckpt.get("remaining_ids", []))
            remaining = [r for r in pool if r["id"] in remaining_ids]
            print(f"  Already completed: {len(completed)}, remaining: {len(remaining)}")
        else:
            print("\nSelecting hard problems...")
            selected = select_hard_problems(pool, args.num_samples, args.seed)
            remaining = selected
            print()

        total = len(remaining) + len(completed)
        print(f"Starting enrichment: {len(remaining)} remaining "
              f"({len(completed)} already done)")
        print(f"API: {args.api_base}  model: {args.model}")
        print(f"Temperature range: [{args.temperature_low}, {args.temperature_high}]")
        print(f"Checkpoint: {checkpoint_path} (every {args.checkpoint_interval})")
        print(f"Workers: {args.workers} concurrent requests")
        print(f"Output: {args.output}\n")

        print_lock = threading.Lock()

        def process_one(rec: Dict) -> Tuple[Dict, Optional[str]]:
            """Process a single problem: call API, return (enriched_record, error_msg)."""
            q = rec["question"]
            q_id = rec["id"]
            src = rec.get("source", "?")
            q_tokens = rec.get("question_tokens", 0)

            if args.delay > 0:
                jitter = rng.uniform(0, args.delay)
                time.sleep(jitter)

            temp = rng.uniform(args.temperature_low, args.temperature_high)

            t0 = time.time()
            try:
                answer = call_minimax(
                    question=q,
                    api_key=api_key,
                    api_base=args.api_base,
                    model=args.model,
                    temperature=temp,
                    max_tokens=args.max_output_tokens,
                )
            except RuntimeError as e:
                with print_lock:
                    print(f"  ERROR [{q_id}]: {e}")
                return {}, str(e)

            elapsed = time.time() - t0
            a_tokens = len(tokenizer.encode(answer, add_special_tokens=False))
            total_tokens = q_tokens + a_tokens

            with print_lock:
                print(f"  [{q_id}] {a_tokens} answer tokens ({len(answer)} chars) "
                      f"in {elapsed:.1f}s (T={temp:.2f})")

            enriched = {
                "id": make_record_id(q_id, args.model),
                "question": q,
                "answer": answer,
                "source": f"enriched_{src}",
                "question_tokens": q_tokens,
                "answer_tokens": a_tokens,
                "total_tokens": total_tokens,
                "original_id": q_id,
                "generator_model": args.model,
            }
            return enriched, None

        errors = 0

        try:
            tasks = list(enumerate(remaining))
            task_idx = 0

            with ThreadPoolExecutor(max_workers=args.workers) as executor:
                futures: Dict[Any, Tuple[int, Dict]] = {}
                for idx, rec in tasks[:args.workers]:
                    futures[executor.submit(process_one, rec)] = (idx, rec)
                task_idx = args.workers

                while futures:
                    for future in as_completed(futures):
                        idx, rec = futures.pop(future)
                        enriched, err = future.result()

                        if err:
                            errors += 1
                            if errors > max(5, len(remaining) * 0.1):
                                print(f"\nToo many errors ({errors}), aborting...")
                                remaining_rest = [r for i, r in tasks if i >= idx]
                                save_checkpoint(checkpoint_path, completed_order,
                                                remaining_rest, vars(args))
                                raise SystemExit(1)
                        else:
                            completed_order.append(enriched)

                        if task_idx < len(tasks):
                            n_idx, n_rec = tasks[task_idx]
                            futures[executor.submit(process_one, n_rec)] = (n_idx, n_rec)
                            task_idx += 1

                        if len(completed_order) % args.checkpoint_interval == 0 and completed_order:
                            remaining_rest = [r for i, r in tasks if i >= task_idx]
                            save_checkpoint(checkpoint_path, completed_order,
                                            remaining_rest, vars(args))
                            with print_lock:
                                print(f"  [Checkpoint: {len(completed_order)}/{total} completed, "
                                      f"{errors} errors]")

        except KeyboardInterrupt:
            print(f"\nInterrupted. Saving checkpoint...")
            remaining_rest = [r for i, r in tasks if i >= task_idx]
            save_checkpoint(checkpoint_path, completed_order, remaining_rest, vars(args))
            print(f"Resume later with: --resume {checkpoint_path}")
            raise SystemExit(0)

        # Clean up checkpoint on success
        if os.path.exists(checkpoint_path):
            os.remove(checkpoint_path)
            print(f"  (checkpoint removed)")

    # ------------------------------------------------------------------
    # Add short-answer records from another pool (optional)
    # ------------------------------------------------------------------
    if do_add_short:
        # If output file already exists, load its records as base
        if not do_enrich and os.path.exists(args.output):
            existing = load_pool(args.output)
            print(f"\nLoading existing enriched pool: {len(existing)} records from {args.output}")
            completed_order = existing

        print(f"\nAdding short-answer records from {args.add_short_from}...")
        short_pool = load_pool(args.add_short_from)
        print(f"  Loaded {len(short_pool)} records from short pool")
        short_records = add_short_records(
            short_pool,
            max_answer_tokens=args.short_max_answer_tokens,
            max_total_tokens=args.short_max_total_tokens,
            max_per_source=args.short_max_per_source,
            seed=args.seed,
        )
        # Dedup against already-completed records
        existing_ids = {r["id"] for r in completed_order}
        new_short = [r for r in short_records if r["id"] not in existing_ids]
        if len(new_short) < len(short_records):
            print(f"  Dedup: {len(short_records) - len(new_short)} short records "
                  f"already in enriched set, removed")
        completed_order.extend(new_short)

    # ------------------------------------------------------------------
    # Save final output
    # ------------------------------------------------------------------
    if completed_order:
        save_records(completed_order, args.output)

        answer_lens = [r["answer_tokens"] for r in completed_order]
        print(f"\nDone. {len(completed_order)} records saved to {args.output}")
        if answer_lens:
            print(f"  Answer tokens: min={min(answer_lens)}, max={max(answer_lens)}, "
                  f"mean={sum(answer_lens) // len(answer_lens)}")
        print(f"  Sources:")
        from collections import Counter
        src_counts = Counter(r["source"] for r in completed_order)
        for s, c in sorted(src_counts.items()):
            print(f"    {s}: {c}")
    else:
        print("\nNo records generated.")


if __name__ == "__main__":
    main()
